/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2013-02-20 20:58:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import javax.servlet.http.HttpSession;

public final class SignIn_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/navmain1.css\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Sign-In</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body\r\n");
      out.write("{\r\n");
      out.write("text-align:center;\r\n");
      out.write("}\r\n");
      out.write(".styled-button-2 {\r\n");
      out.write("\t-webkit-box-shadow:rgba(0,0,0,0.0.1) 0 1px 0 0;\r\n");
      out.write("\t-moz-box-shadow:rgba(0,0,0,0.0.1) 0 1px 0 0;\r\n");
      out.write("\tbox-shadow:rgba(0,0,0,0.0.1) 0 1px 0 0;\r\n");
      out.write("\tbackground-color:#191970;\r\n");
      out.write("\tborder:1px solid #29447E;\r\n");
      out.write("\tfont-family:'Lucida Grande',Tahoma,Verdana,Arial,sans-serif;\r\n");
      out.write("\tfont-size:12px;\r\n");
      out.write("\tfont-weight:700;\r\n");
      out.write("\tpadding:2px 6px;\r\n");
      out.write("\theight:28px;\r\n");
      out.write("\tcolor:#fff;\r\n");
      out.write("\tborder-radius:5px;\r\n");
      out.write("\t-moz-border-radius:5px;\r\n");
      out.write("\t-webkit-border-radius:5px\r\n");
      out.write("}\r\n");
      out.write(".boxBody\r\n");
      out.write("{\r\n");
      out.write("    background:\t #D3D3D3;\r\n");
      out.write("    border-top:2px solid #dde0e8;\r\n");
      out.write("    border-bottom:2px solid #dde0e8;\r\n");
      out.write("    padding:10px 30px;\r\n");
      out.write("    margin-left: 4%;\r\n");
      out.write("\tmargin-right: 70%;\r\n");
      out.write("\tborder-radius: 40px / 20px ;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function validateLogin()\r\n");
      out.write("\r\n");
      out.write("{\r\n");
      out.write("\t// var numbers = /^[0-9]+$/;  \r\n");
      out.write("    if(document.form1.user.value==\"\")\r\n");
      out.write("    {\r\n");
      out.write("      alert(\"User Name should not be left blank\");\r\n");
      out.write("      document.form1.user.focus();\r\n");
      out.write("      return false;\r\n");
      out.write("    }\r\n");
      out.write("    else if(document.form1.pwd.value==\"\")\r\n");
      out.write("    {\r\n");
      out.write("      alert(\"Password should not be left blank\");\r\n");
      out.write("      document.form1.pwd.focus();\r\n");
      out.write("      return false;\r\n");
      out.write("    }\r\n");
      out.write("    else if (!(/^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$/.test(form1.uname.value)))\r\n");
      out.write("    {\r\n");
      out.write("        alert(\"UserName should be in E-Mail Foramt\");\r\n");
      out.write("        document.form1.uname.focus();\r\n");
      out.write("\r\n");
      out.write("    \treturn false;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body  background=\"Spiderman.jpg\" >\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<div align=left>\r\n");
      out.write(" &nbsp;&nbsp; &nbsp; &nbsp;<font size=\"6\" color=\"#fff\" >Video Library Management</font>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write(" &nbsp; &nbsp; <font size=\"6\" color=\"#fff\" align=left>Login</font>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br><br><br><br><br>\r\n");
      out.write("</div>\r\n");
      out.write("<fieldset class=\"boxBody\">\r\n");
      out.write("<br>\r\n");
      out.write("<div align=center>\r\n");
      out.write("<form name=\"form1\" method=\"post\"  action=\"SignInController\" onSubmit=\"return validateLogin()\">\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("<tr height=\"50\">\r\n");
      out.write("<td><div class=\"form-row\"><span class=\"label\">  User Name*</span></td><td><input type=\"text\" name=\"user\"/> </td></div>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr height=\"50\">\r\n");
      out.write("<td><div class=\"form-row\"><span class=\"label\">  Password*</span></td><td><input type=\"password\" name=\"pwd\"/> </td></div>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr height=\"50\">\r\n");
      out.write("<td><div class=\"form-row\"><input type=\"submit\" class=\"styled-button-2\" value=\"Login\" > </div></td>\r\n");
      out.write("</form>\r\n");
      out.write("<td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form name=myForm method=\"post\" action= \"SignUp.jsp\" onsubmit=\"\">\r\n");
      out.write("<input type=\"submit\" class=\"styled-button-2\" value=\"Sign Up\">\r\n");
      out.write("</form>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("</div>\r\n");
      out.write("</fieldset>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</frameset>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
