/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2013-02-20 21:00:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class updateMovie_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write("td {\r\n");
      out.write(" border: solid 1px black;\r\n");
      out.write("}\r\n");
      out.write("tr{\r\n");
      out.write(" border: solid 1px black;\r\n");
      out.write("}\r\n");
      out.write("table{\r\n");
      out.write("border: solid 1px black;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("function validateInput()\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tvar x1=document.forms[\"searchMovies\"][\"movname\"].value;\r\n");
      out.write("\tvar x2=document.forms[\"searchMovies\"][\"movbanner\"].value;\r\n");
      out.write("\tvar x3=document.forms[\"searchMovies\"][\"releasedate\"].value;\r\n");
      out.write("\tvar x4=document.forms[\"searchMovies\"][\"category\"].value;\r\n");
      out.write("\t\r\n");
      out.write("\tif (x1==\"\" && x2==\"\" && x3==\"\" && x4==\"\")\r\n");
      out.write("\t  {\r\n");
      out.write("\t  alert(\"Not all fields can be Null !!!\");\r\n");
      out.write("\t  return false;\r\n");
      out.write("\t  }\r\n");
      out.write("}\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Update Movie !!!</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"navbar1\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "adminhome.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br><br><br><br><br><br><br><br><br><br><br><br>\r\n");
      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("\r\n");

String str = null;
str=session.getAttribute("updatemovmsg").toString();

if (str.equals("msg")){}
else{

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("alert(\"");
      out.print(session.getAttribute("updatemovmsg"));
      out.write("\");\r\n");
      out.write("</script>\r\n");
	
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<b>Search for Movie to be Updated !!!</b> \r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<form id=\"searchMovies\" onsubmit=\"return validateInput()\" method=\"post\" action=\"searchForUpdate\">\r\n");
      out.write("\r\n");
      out.write("<table align=\"center\" border=\"1\">\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<th>Field</th>\r\n");
      out.write("<th>Value</th>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("Movie Name \r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"text\" name=\"movname\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("Movie Banner \r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"text\" name=\"movbanner\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("Release Date \r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"text\" name=\"releasedate\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("Category\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<select name=\"category\">\r\n");
      out.write("<option value=\"\">Select Category</option>\r\n");
      out.write("<option value=\"Comedy\">Comedy</option>\r\n");
      out.write("<option value=\"Drama\">Drama</option>\r\n");
      out.write("<option value=\"Action\">Action</option>\r\n");
      out.write("<option value=\"Romance\">Romance</option>\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("<input class=\"submit\" type=\"submit\" value=\"Search Movie\" >\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
